Repository kowainik/hakyll-shortcut-links, pull requests merged in 2019-05, with the labels that each got.

#7 [#6] Implement better error reporting
  hakyll-shortcut-links.cabal
  src/Hakyll/Shortcut/Links.hs
  test/Spec.hs
Labels: enhancement, pandoc

#8 Add unit test on parsing
  hakyll-shortcut-links.cabal
  test/Spec.hs
  test/Test/Parser.hs
Labels: parser, tests

#9 [#4] Add tests for links expanding
  hakyll-shortcut-links.cabal
  test/Spec.hs
  test/Test/Links.hs
  test/Test/Parser.hs
Labels: tests

#11 Reexport from s-l, add haddock
  CHANGELOG.md
  hakyll-shortcut-links.cabal
  src/Hakyll/Shortcut/Links.hs
  src/Hakyll/ShortcutLinks.hs
  src/Hakyll/ShortcutLinks/Parser.hs
  test/Test/Links.hs
  test/Test/Parser.hs
Labels: docs, shortcut-links

#12 [#10] Improve title handling
  src/Hakyll/ShortcutLinks.hs
  test/Test/Links.hs
Labels: enhancement, tests

#13 [#2] Add README
  README.md
Labels: docs

#15 [#14] Upgrade to GHC-8.6.5
  .travis.yml
  README.md
  hakyll-shortcut-links.cabal
Labels: enhancement
